[package]
name = "logger-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.0"

[lib]
crate-type=["staticlib", "cdylib"]
