[package]
name = "metrics-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
prometheus = "0.13.3"

[lib]
crate-type=["staticlib", "cdylib"]
